name = "gleaner"
version = "0.1.0"
defaultTargets = ["main"]

# [[require]]
# name = "mathlib"
# scope = "leanprover-community"

[[lean_lib]]
name = "Application"

[[lean_lib]]
name = "Inductive"

[[lean_lib]]
name = "Structure"

[[lean_exe]]
name = "main"
root = "Main"

[[lean_exe]]
name = "doug"
root = "Doug"
